name: local_auth_darwin_example
description: Demonstrates how to use the local_auth_darwin plugin.
publish_to: none

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  local_auth_darwin:
    # When depending on this package from a real application you should use:
    #   local_auth_darwin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  local_auth_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

# FOR TESTING AND INITIAL REVIEW ONLY. DO NOT MERGE.
# See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins
dependency_overrides:
   {google_maps_flutter_ios: {path: ../../../../google_maps_flutter/google_maps_flutter_ios}, google_maps_flutter_platform_interface: {path: ../../../../google_maps_flutter/google_maps_flutter_platform_interface}}
